snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%snc.redis_dsn%"
        cache:
            type: predis
            alias: cache
            dsn: "%snc.redis_dsn%/1"
        sector:
            type: predis
            alias: sector
            dsn: "%snc.redis_dsn%/2"
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default
            document_manager: default
        result_cache:
            client: cache
            entity_manager: default
        query_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default